version: 2
jobs:
  build:
    docker: 
      # the primary container, where your job's commands are run
      - image: circleci/node

    steps:
      - checkout
      - run:
          name: Compile React.js
          command: |
            npm i --quiet
      - run:
          name: Create Artifact
          command: |
            mkdir /tmp/artifacts
            cp ./app/.babelrc /tmp/artifacts
      - store_artifacts:
          path: /tmp/artifacts
          destination: build

workflows:
  version: 2
  build-deploy:
    jobs:
      - build:
        filters:
          branches:
            only: 
              - develop