version: 2
jobs:
  build:
    docker: 
      # the primary container, where your job's commands are run
      - image: circleci/node:4.8.2 
    steps:
      - checkout
      - run:
          name: Compile React.js
          command: |
            npm i --quiet
            npm run react:build
      - run:
          name: Create Artifact
          command: |
            mkdir /tmp/artifacts
            cp ./app/public
      - store_artifacts:
          path: /tmp/artifacts
          destination: build